shorturl/urls.py
from django.conf.urls import include, url
from . import views
 
urlpatterns = [
    url(r'^$', views.index,name='home'),
    # for our home/index pag1e
 
    url(r'^(?P<short_id>\w{1,11})$', views.redirect_original, name='redirectoriginal'),
    # when short URL is requested it redirects to original URL
 
    url(r'^makeshort/$', views.shorten_url, name='shortenurl'),
    # this will create a URL's short id and return the short URL
    ]

shortweb/urls.py
from django.conf.urls import url,include
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('shorturl.urls', namespace='shorturl')),
]

shorturl/models.py
from django.db import models

# Create your models here.
class urls(models.Model):
    short_id = models.SlugField(max_length=6,primary_key=True)
    httpurl = models.URLField(max_length=200)
    pub_date = models.DateTimeField(auto_now=True)
    count = models.IntegerField(default=0)

    def __str__(self):
        return self.httpurl

    class Meta:
    	verbose_name_plural = 'urls'

shorturl/views.py
from django.shortcuts import render
from django.forms import URLField,EmailField
from django.shortcuts import render_to_response, get_object_or_404
import random, string, json
from shorturl.models import urls
from django.http import HttpResponsePermanentRedirect, HttpResponse
from django.conf import settings
from django.template.context_processors import csrf
from django.core.exceptions import ValidationError
record = {} 
def index(request):
    c = {}
    c.update(csrf(request))
    return render_to_response('shorturl/index.html', c)
 
def redirect_original(request, short_id):
    url = get_object_or_404(urls, pk=short_id) # get object, if not found return 404 error
    url.count += 1
    url.save()
    return HttpResponsePermanentRedirect(url.httpurl)
 
def shorten_url(request):
	url = request.POST.get("url", '')
	alias = request.POST.get("alias")
	valid_url,url=validate_url(url)
	if valid_url:
		if alias !='':
			for rec in record:
				if record[rec]==alias:
					return HttpResponse(json.dumps({"error":"error occurs", 'alias':-1, 'url':url}),content_type="application/json")

		if url in record:
			short_id = record.get(url)
			if alias !='' and alias != short_id:
				b = urls.objects.get(pk=short_id)
				b.short_id=alias
				b.save()		
				short_id = alias
				record[url]=alias
			response_data = {}
			response_data['url'] = settings.SITE_URL + "/" + short_id
			return HttpResponse(json.dumps(response_data),  content_type="application/json")
		else:
			# check whether input is already short
			if is_already_short(url):
				response_data = {}
				return HttpResponse(json.dumps({"already_short": True}), content_type="application/json")
			elif alias == '':
				short_id = get_short_code()
				record.update({url:short_id})
				b = urls(httpurl=url, short_id=short_id)
				b.save()
				response_data = {}
				response_data['url'] = settings.SITE_URL + "/" + short_id
				return HttpResponse(json.dumps(response_data),  content_type="application/json")

			else:
				record.update({url:alias})
				b = urls(httpurl=url, short_id=alias)
				b.save()
				response_data={}
				response_data['url'] = settings.SITE_URL + "/" + alias
				return HttpResponse(json.dumps(response_data),  content_type="application/json")
	return HttpResponse(json.dumps({"error": "error occurs", "valid_url":valid_url,'url':url}), content_type="application/json")

def get_short_code():
    length = 6
    char = string.ascii_uppercase + string.digits + string.ascii_lowercase
    # if the randomly generated short_id is used then generate next
    while True:
        short_id = ''.join(random.choice(char) for _ in range(length))
        try:
            temp = urls.objects.get(pk=short_id)
        except:
            return short_id

'''
To check whether given URL is already short by checking existence of some popular URL shortners as a substring in URL

inputs 
url -> url link input

output
True -> if url is already short
False -> if url is not short
'''
def is_already_short(url):
    popular_shortening_urls = [
        'bit.ly/',
        'goo.gl/',
        'ow.ly/',
        'is.gd/',
        'buff.ly/',
        'adf.ly/',
        'tinyurl.com/',
        'bit.do/',
        'mcaf.ee/',
        't.co/',
        'tiny.cc/',
        'shorte.st/',
        'idek.net/',
        'po.st/',
        'yep.it/',
        'tr.im/',
        settings.SITE_URL,
    ]
    for shortening_url in popular_shortening_urls:
        if shortening_url in url:
            return True
    return False

def validate_url(url):
	protocols=[
		'http://',
		'https://',
	]
	flag=0
	url_form_field = URLField()
	email_field = EmailField()
	try :
		email_field.clean(url)
	except ValidationError:
		if url!='':
			for protocol in protocols:
				n=len(protocol)
				if url[0:n]==protocol:
					flag=1
					break
			if flag==0:
				flag1=1
				for protocol in protocols:
					new_url = protocol+url
					try:
						new_url == url_form_field.clean(new_url)
					except ValidationError:
						flag1=0
					else:
						url=new_url
						break
				if flag1==1:
					return True,url
				return False,url
			return True,url
		return False,url
	else:
		return False,url

shorturl/templates/shorturl/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}Welcome to mysite{% endblock %}</title>	
	<!--Let browser know website is optimized for mobile-->
	<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
	<!-- import google Icon Font -->
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<!--Import materialize.css-->
	<link type="text/css" rel="stylesheet" href="{% static 'shorturl/css/materialize.min.css' %}"  media="screen,projection"/>
	<!-- Import custom css -->
	<link rel="stylesheet" type="text/css" href="{% static 'shorturl/css/custom.css' %}" />
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
	<!-- Import clipboard.js -->
	<script src="https://cdn.jsdelivr.net/npm/clipboard@1/dist/clipboard.min.js"></script>
	<!-- Import Javascript file for materialize -->
	<script type="text/javascript" src="{% static 'shorturl/js/materialize.min.js' %}"></script>
	<!-- Import Javascript file for QR Code -->
	<script type="text/javascript" src="{% static 'shorturl/js/jquery.qrcode.min.js' %}"></script>
</head>
<script type="text/javascript">
	// intializing side navbar for small screen devices
	$( document ).ready(function(){
		$(".button-collapse").sideNav();
	});

	var clipboard;
	$(function() {
		$('#submitButton').click(function() {
			$.ajax({
				type: "POST",
				url: "/makeshort/",
				data: {
					'url' : $('#url').val(),
					'csrfmiddlewaretoken' : $("input[name=csrfmiddlewaretoken]").val(),
					'alias' : $('#alias').val(),
				},
				success: returnSuccess,
				dataType: 'json'
			});
		});
	});

	function returnSuccess(data, textStatus, jqXHR) {
		if(data.url && !data.error) {
			var url_result_html = "<a target=_blank href='"+data.url+"'>"+data.url+"</a>";
			$('#url-result').html(url_result_html);
			$('#url').val("");
			$('#alias').val("");
 	 		$('#clear_btn').addClass('hide');

			// Button
			clipboard = new Clipboard('#clip_copy', {
 				text: function(trigger){
 					return data.url;
 				}		
 	 		});
			$('#clip_copy').removeClass("disabled");

			// QR Code
			$('#qr-code').html('');
			$('#qr-code').qrcode({
				width: 80, height: 80,		// Select width and height of QR Code here
				text: data.url
			});
		} 
    else if(data.already_short) {
			// show pop up error message
			// Materialize.toast(message, displayLength, className, completeCallback);
			var toast_content = "Entered URL is already short.";
			Materialize.toast(toast_content, 3000, 'red lighten-1');
			$('#qr-code').html('');

		} 
    else {	
    		if (data.url=='') $('#url-result').text("Do not submit blank.");
    		else if (data.alias==-1) $('#url-result').text("Alias already in use. Try another.");
    		else $('#url-result').text("Enter a valid URL");
    		$('#qr-code').html('');
			clipboard.destroy(); 
		}

	}

	function show_clear_btn(){
		var url_text=$('#url').val();
		if (url_text != '' && $('#clear_btn').hasClass('hide')){
			$('#clear_btn').removeClass('hide');
		}
		else if(url_text == ''){
			$('#clear_btn').addClass('hide');
		}
	}

	function clear_url(){
		$('#url').val('');
		$('#clear_btn').addClass('hide');
	}
	
</script>
<body>
	<!-- navbar -->
	<nav>
		<div class="nav-wrapper row white grey-text">
			<div class="col s12">
				<a href="{% url 'shorturl:home' %}" class="brand-logo ">URL Shortener</a>
				<a href="#" data-activates="mobile-demo" class="button-collapse grey-text"><i class="material-icons">menu</i></a>
				<!-- for large screen -->
				<ul class="right hide-on-med-and-down">
					<li><a href="https://github.com/modihere/url-shortener" target="blank" class="btn grey">Contribute</a></li>
				</ul>
				<!-- for small screen -->
				<ul class="side-nav" id="mobile-demo">
					<li><a href="https://github.com/modihere/url-shortener" target="blank" class="btn grey">Contribute</a></li>
				</ul>
			</div>
		</div>
	</nav>
	<!-- //navbar -->
	<div class="main">
			{% block content %}
			{% endblock %}
	</div>

	<!-- footer -->
	<footer class="page-footer white">
		<div class="row grey-text">
			<div class="col s4 m3 l2"> 
				<a href="https://gitter.im/url_shortener/Lobby" target="blank">Contact</a>
			</div>
		</div>
	</footer>
</body>
</html>

shorturl/templates/shorturl/index.html
{% extends "shorturl/base.html" %}
{% load staticfiles %}
{% block title %}URL Shortner - Make your URL shorter!{% endblock %}
  
{% block content %}
<!-- input -->

<div class="input-section blue darken-2">
	<div class="container row">
		<div class="card url-input-container col s12">
			<input type="text" name="url" id="url" placeholder="Paste a link to shorten it, generates QR code too" autocomplete="off" spellcheck="false" class="url-input"  onkeydown = "if(event.keyCode == 13)document.getElementById('submitButton').click()" onkeyup="show_clear_btn();">
			<button id='clear_btn' class="url-submit btn btn-large white text-grey hide" onclick="clear_url();">X</button>
		</div>
		<div class="card url-input-container col s6 offset-m3">
			<input type="text" name="alias" id="alias" class="url-input" placeholder="Enter your alias (optional)" autocomplete="off" spellcheck="false" maxlength="10">
		</div>
		<div class="url-submit-container col s12">
			{% csrf_token %}
			<button id="submitButton" class="url-submit btn white text-grey">Shorten It</button>
		</div>

		<div class="url-output col l6 offset-l3 m8 offset-m2 s12 ">
			<div class="card horizontal grey lighten-4 ">
				<div class="card-image" style="padding: 10px 10px 5px 10px">
					<div id="qr-code"></div>
				</div>
				<div class="card-content valign-wrapper" id="url-result">
					Enter the URL above and click SHORTEN IT!
				</div>
				<a class="btn-floating halfway-fab waves-effect waves-light red disabled" id="clip_copy" title="Copy to clipboard">
					<i class="material-icons">content_copy</i>
				</a>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
	document.getElementById('alias').onkeydown = function (event) {
  var event = event || window.event;  // get event object
  var key = event.keyCode || event.which; // get key cross-browser
  
  if (key == 32) { //Space bar key code
    //Prevent default action, which is inserting space
    if (event.preventDefault) event.preventDefault(); //normal browsers
    event.returnValue = false; //IE
  }
};
</script>

<!-- //input -->
<!-- Description -->
<div class="container row description-section text-center">
	<div class="section s12">
		<h3>Redefining URL</h3>
		<p>Cut your links, into MUCH shorter ones, Just one click to go..!!</p>
	</div>
	<div class="section col l4 m6 s12">
		<i class="small material-icons">insert_link</i>
		<h5>Shorten</h5>
		<p>Shorten your URL so it’s ready to be shared everywhere</p>
	</div>
	<div class="section col l4 m6 s12">
		<img src={% static 'shorturl/image/qr.svg' %} style='width:32px;height:32px;' />
		<h5>QR Code</h5>
		<p>Generates QR code for convenience and can be shared easily</p>
	</div>
	<div class="section col l4 m6 s12">
		<i class="small material-icons">people</i>
		<h5>Open Source</h5>
		<p>URL Shortener is free and open source</p>
	</div>
</div>
{% endblock %}